module Sleepyshark
  module Officina
    module Mcp
      class AllowedTool < Data
        attr_reader name: String
        attr_reader kind: Symbol
        attr_reader needs_approval: bool

        def self.new: (name: String, ?kind: Symbol, ?needs_approval: bool) -> instance

        def initialize: (name: String, ?kind: Symbol, ?needs_approval: bool) -> void
      end
    end
  end
end
