module Sleepyshark
  module Officina
    module Mcp
      module RawJson
        SCALAR: Regexp
        BETWEEN: Regexp
        OPENING: Regexp
        CLOSING: Regexp

        def self.member: (String text, String name) -> String

        def self.members: (String text) -> Hash[String, String]

        def self.elements: (String text) -> Array[String]

        def self.opened: (String text) -> StringScanner

        def self.closing: (StringScanner scanner) -> Integer?

        def self.value: (StringScanner scanner) -> String

        def self.skip_nested: (StringScanner scanner) -> void
      end
    end
  end
end
