module Sleepyshark
  module Officina
    module Testing
      class FakeMcpTool < Data
        attr_reader name: String
        attr_reader handler: ^(Hash[String, untyped] arguments) -> String
        attr_reader description: String
        attr_reader input_schema: Hash[String, untyped]

        def self.new: (name: String, handler: ^(Hash[String, untyped] arguments) -> String, ?description: String,
                       ?input_schema: Hash[String, untyped]) -> instance

        def initialize: (name: String, handler: ^(Hash[String, untyped] arguments) -> String, ?description: String,
                         ?input_schema: Hash[String, untyped]) -> void
      end
    end
  end
end
