<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sleepyshark.Officina.Core\Sleepyshark.Officina.Core.csproj" />
    <ProjectReference Include="..\..\src\Sleepyshark.Officina.Storage.Sqlite\Sleepyshark.Officina.Storage.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Sleepyshark.Officina.Testing\Sleepyshark.Officina.Testing.csproj" />
  </ItemGroup>

</Project>
