# frozen_string_literal: true

require_relative 'officina/version'
require_relative 'officina/error'
require_relative 'officina/usage'
require_relative 'officina/cancellation'
require_relative 'officina/tool'
require_relative 'officina/tool_call'
require_relative 'officina/tool_result'
require_relative 'officina/block'
require_relative 'officina/message'
require_relative 'officina/request'
require_relative 'officina/reply'
require_relative 'officina/text_delta'
require_relative 'officina/usage_reported'
require_relative 'officina/conversation_appended'
require_relative 'officina/completed'
require_relative 'officina/stopped'
require_relative 'officina/failed'
require_relative 'officina/tool_call_started'
require_relative 'officina/approval_asked'
require_relative 'officina/approval_answered'
require_relative 'officina/tool_call_finished'
require_relative 'officina/approval'
require_relative 'officina/audit_entry'
require_relative 'officina/json_lines_audit_sink'
require_relative 'officina/secrets'
require_relative 'officina/conversation'
require_relative 'officina/audit_recorder'
require_relative 'officina/call_report'
require_relative 'officina/approval_desk'
require_relative 'officina/quiet_thread'
require_relative 'officina/running_reads'
require_relative 'officina/tool_pipeline'
require_relative 'officina/reply_outcome'
require_relative 'officina/reporter'
require_relative 'officina/tool_step'
require_relative 'officina/run_engine'
require_relative 'officina/agent'
require_relative 'officina/schema_error'
require_relative 'officina/dotnet_json'
require_relative 'officina/schema_subset'
require_relative 'officina/schema'
require_relative 'officina/input'

module Sleepyshark
  # Officina's core: a purpose-neutral library for building agentic applications.
  module Officina
  end
end
