module Sleepyshark
  module Officina
    class ApprovalAsked < Data
      attr_reader call: ToolCall

      def self.new: (call: ToolCall) -> instance


      def initialize: (call: ToolCall) -> void
    end
  end
end
