module Sleepyshark
  module Officina
    class Block < Data
      TOKEN: Regexp
      HTML: Hash[String, String]

      attr_reader text: String?
      attr_reader raw: String?
      attr_reader tool_call: ToolCall?
      attr_reader tool_result: ToolResult?

      def initialize: (?text: String?, ?raw: String?, ?tool_call: ToolCall?, ?tool_result: ToolResult?) -> void

      def self.canonical: (String json) -> String
    end
  end
end
