module Sleepyshark
  module Officina
    class Cancellation
      @lock: Thread::Mutex
      @cancelled: bool
      @callbacks: Array[^() -> void]

      def initialize: () -> void

      def cancel: () -> void

      def cancelled?: () -> bool

      def on_cancel: () { () -> void } -> void
    end
  end
end
