module Sleepyshark
  module Officina
    class Completed < Data
      attr_reader text: String
      attr_reader output: Data?
      attr_reader usage: Usage
      attr_reader cost: BigDecimal
      attr_reader model_calls: Integer
      attr_reader tool_calls: Integer
      attr_reader duration: Float

      def self.new: (text: String, ?output: Data?, ?usage: Usage, ?cost: BigDecimal, ?model_calls: Integer, ?tool_calls: Integer,
                     ?duration: Float) -> instance

      def initialize: (text: String, ?output: Data?, ?usage: Usage, ?cost: BigDecimal, ?model_calls: Integer, ?tool_calls: Integer,
                       ?duration: Float) -> void
    end
  end
end
