module Sleepyshark
  module Officina
    class Request < Data
      attr_reader tools: Array[Tool]
      attr_reader instructions: String
      attr_reader messages: Array[Message]

      def initialize: (tools: Array[Tool], instructions: String, messages: Array[Message]) -> void
    end
  end
end
