module Sleepyshark
  module Officina
    class Tool < Data
      attr_reader name: String
      attr_reader description: String
      attr_reader input_schema: String

      def initialize: (name: String, description: String, input_schema: String) -> void

      private

      def object?: (String json) -> bool
    end
  end
end
