<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- For the generated Linux system calls of LinuxCopyFile. -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sleepyshark.Officina.Core\Sleepyshark.Officina.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sleepyshark.Officina.Workspace.Tests" />
  </ItemGroup>

</Project>
