module Bookshop
  class Application
    @database: Database
    @telemetry: Telemetry
    @console: Console

    def initialize: (database: Database, telemetry: Telemetry, console: Console) -> void
    def run: () -> void
    def close: () -> void
  end
end
